/**
 * Action Types Constants
 */
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const START_FETCH_CURRENT_WEATHER = 'START_FETCH_CURRENT_WEATHER';
export const END_FETCH_CURRENT_WEATHER = 'END_FETCH_CURRENT_WEATHER';
export const ERROR_FETCH_CURRENT_WEATHER = 'END_FETCH_CURRENT_WEATHER';

export const REQUEST_ERROR = 'REQUEST_ERROR';
